name: verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install deps (CI)
        run: npm ci

      - name: Normalize check (mojibake/marks)
        run: npm run normalize:check

      - name: Typecheck
        run: npm run typecheck

      - name: Dry build
        run: npm run build:dry

